spring:
  datasource:
    url: jdbc:mariadb://database-1.cxkkamogkg22.ap-northeast-2.rds.amazonaws.com:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: dltkdgur12
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  config:
    activate:
      on-profile: dev